# Generated by Django 4.2.9 on 2024-02-12 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_vacancy_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='min_expierence',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
