# Generated by Django 4.2.9 on 2024-02-12 09:44

from django.db import migrations, models
import vacancies.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_vacancy_min_expierence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='min_expierence',
            new_name='min_experience',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='updated_at',
            field=models.DateField(null=True, validators=[vacancies.models.updated_date]),
        ),
    ]
